### ISSUE TITLE
Issues with latest release

### ISSUE THREAD

**Issue by naxir121** [dwaithe/FCS_point_correlator#15]
Dear Dom,
Many thanks for the new release of the software. We have encountered a few issues that I wanted to bring up. Everything I will talk about is on the "Fit Function" Tab. 
1- When I open the program, the parameters windows do not stretch properly (See Picture 1). This makes it difficult to play with the parameters. 
2- When I load a correlated fcs or sin file, the y-axis are always fixed between 0 and 1, in the old versions it used to change so that we could immediately see the curves as fcs files start from 1 (See Picture 2). 
3- To solve the issue number 2, I go to "Edit Axis..." button and edit the axis, then press "Keep Scale" so that next time I load a file, it does not change, but still when I load a new file, it immediately goes back to 0-1 y-axis format. It is very time-consuming to edit the axis every time. 

![Focus1](https://user-images.githubusercontent.com/6042119/93860065-c65a1680-fcbe-11ea-9b96-fd294e2e080e.jpg)
![Focus2](https://user-images.githubusercontent.com/6042119/93860068-c6f2ad00-fcbe-11ea-9a4a-5ed7c6fb6803.jpg)

Best wishes,
Erdinc

**Comment by dwaithe** [comment]
Hi Erdinc,
I fixed the bugs you mentioned. Thanks for registering them. Please find the latest release:
https://github.com/dwaithe/FCS_point_correlator/releases/tag/1.15.175
Best,
Dominic.
