### ISSUE TITLE
Corrupted documentation files

### ISSUE THREAD

**Issue by frapaezla** [dwaithe/FCS_point_correlator#16]
In the latest release, the documentation file FoCuS-point-correlation-manual.pdf ends abruptly at page 6.

**Comment by dwaithe** [comment]
Hi frapaezla,
Sorry for my slow reply. In the latest release you will find a complete manual, for both the focuspoint correlation and fitting sections.
https://github.com/dwaithe/FCS_point_correlator/releases/tag/1.15.181
Thanks for your patience.
Best,
Dominic
