### ISSUE TITLE
cpm (kHz) is actually in Hz

### ISSUE THREAD

**Issue by Faldalf** [dwaithe/FCS_point_correlator#18]
Hi Dominic, 

I noticed recently that the counts per molecule (calculated by FCS as G(0) * average_counts) is actually in Hz and not kHz as stated when the file parameters are copied into Excel. I attach an example measurement of AlexaFluor488 in water acquired at a Zeiss780. I expect counts per molcule round 25-25 kHz but obtain a thousandfold of that. 
[Calibration_Dominic.zip](https://github.com/dwaithe/FCS_point_correlator/files/6135065/Calibration_Dominic.zip)

Not a big issue but would be great to have the units corrected or the number divided by 1000.

Many thanks, 
Falk

**Comment by dwaithe** [comment]
Thanks. That’s clear will correct it.

**Comment by dwaithe** [comment]
Hi Falk, When I check your files, they are coming out at 218 kHz once the correction is in place (218,000 beforehand). Can you double-check what you expect the values to be. The /1000 correction won't be sufficient if you are certain about your counts and I will have to take a deeper dive into the problem.
Best,
Dominic

**Comment by dwaithe** [comment]
Hi Falk, please ignore my previous (now deleted) message. I am happy with this new correction.  The .fcs files are not documented as far as I can see and so I can't be 100% sure of the calculated values we are getting. We do now seem to be very consistent with your expected values. I have updated the github, and will produce new release of software shortly. Once fit I receive the following values: 

24.6580532
24.7409599
25.1287313
24.9794853
24.9512848
24.7009012
24.6789809
24.7053799
24.0904678
24.9215365
24.7554318
24.9288097
24.7676025
25.2409996
24.6815533

Thanks again. 
Dominic.

**Comment by Faldalf** [comment]
Hi Dominic, 

awesome - thank you very much. That looks very reasonable in comparison to the values you get directly from the 780 by fitting or moment analysis. 

Many thanks again!
Best, 
Falk
