### ISSUE TITLE
FoCuS_point crashes when saving fittingpara to clipboard

### ISSUE THREAD

**Issue by Faldalf** [dwaithe/FCS_point_correlator#19]
Hi Dominic, 

the most recent version of the software seems to crash when I save the fitting parameters to the clipboard. That worked fine with all other FoCuS_point/scan versions I have tried in the past. I encountered the issue in realease 1_15_181

Error message from the console: 
![Error_CopyParameters](https://user-images.githubusercontent.com/66516920/111036314-8d516200-8416-11eb-8662-9f6c0ba873ed.PNG)

Many thanks.
Best, 
Falk

**Comment by dwaithe** [comment]
Thanks, I fixed this in the latest push. It will be fixed in the next release.
