### ISSUE TITLE
Numpy 0.13 support in `correlation_methods.py`

### ISSUE THREAD

**Issue by paulmueller** [dwaithe/FCS_point_correlator#2]
`correlation_methods.py` uses numpy indexing that causes a `VisibleDeprecationWarning` starting NumPy 0.10. In NumPy 0.13, the warning becomes an error (see e.g. [here](https://stackoverflow.com/questions/33098765/visibledeprecationwarning-boolean-index-did-not-match-indexed-array-along-dimen)).

I fixed this in PyCorrFit using `numpy.where`:
https://github.com/FCS-analysis/PyCorrFit/commit/132991c7a2950c0c380c6df6edf433f61911a6db

**Comment by dwaithe** [comment]
Thanks Paul,
I have incorporated your changes. Thanks for taking the time to  do that.
Best,
Dominic
