### ISSUE TITLE
Reading, correlating and gating .ptu-files exported from Leica FALCON

### ISSUE THREAD

**Issue by Faldalf** [dwaithe/FCS_point_correlator#20]
Hi Dominic, 

our Leica SP8 was coupled to PicoQuant electronics and we used FoCuS_point to correlate and analyse our data. Since we upgraded to FALCON we used the internatl fitting routine. However, we can also export the raw photon data as .ptu-files. It would be super handy to be able to analyse the FCS data offline on a personal computer. Unfortuantely, there seems to be a problem with reading these files into FoCuS. 

Under FoCuS_point 1_13_146, the files are read in (and correlated) fine. Unfortunately, gating does not work but is of utmost important for STED-FCS. The error message reads "subPicoObject instance has no attribute 'dTimeArr'

Under the most recent release (1_16_197), the software crashes upon attempting to load a FALCON ptu file. The error message reads "picoObject object has no attribute 'autotime'".

Using the example code from PicoQuant (https://github.com/PicoQuant/PicoQuant-Time-Tagged-File-Format-Demos/blob/master/PTU/Python/Read_PTU.py) and your tttr2xfcs function, I can read, gate and correlate the data from Python. It would of course be awesome to do this again from within the FoCuS GUI. 

Here, I attach example files acquired at 40 and 80 MHz WLL repetition rate at our Leica SP8 FALCON exported to .ptu. 
[FALCON_ptu_examples.zip](https://github.com/dwaithe/FCS_point_correlator/files/6254629/FALCON_ptu_examples.zip)

Many, many thanks for your help. 
Best, 
Falk

**Comment by dwaithe** [comment]
Hi Falk,
Should be fixed now. Please find the software:
https://github.com/dwaithe/FCS_point_correlator/releases/tag/1.16.198
Thanks for pointing out the problem and sharing the file.
Best,
Dominic.
