### ISSUE TITLE
Loading .ptu file leads to crash with error - "utf-8 codec can't decode byte 0xb5 in position 38: invalid start byte"

### ISSUE THREAD

**Issue by lauracmurphy** [dwaithe/FCS_point_correlator#21]
Hi @dwaithe,

Having an issue that when I load .ptu into either 1_15 and 1_16, the software immediately crashes and I get the following error messsage.

unicodedecodeerror 'utf-8' codec can't decode byte 0xb5 in position 38: invalid start byte

I don't get the error in 1_13.

Happy to provide an example file if you want. I've been trying with files from a Leica SP5 using Symphotime 2.4.4874.

**Comment by dwaithe** [comment]
Hi Laura,
Please try with the latest version (if you haven't already):
https://github.com/dwaithe/FCS_point_correlator/releases/tag/1.16.199
If it doesn't work, then please do send me a file, either attach it here, or email it to me.
Thanks,
Dom.

**Comment by lauracmurphy** [comment]
Yeah, tried most recent. File attached.

[a488_plastic_pmt2_3_1_1_1.zip](https://github.com/dwaithe/FCS_point_correlator/files/6426258/a488_plastic_pmt2_3_1_1_1.zip)

**Comment by lauracmurphy** [comment]
Thanks a lot for the fix Dominic! 

https://github.com/dwaithe/FCS_scanning_correlator/issues/6#issuecomment-832624308
