### ISSUE TITLE
AttributeError: 'int' object has no attribute 'astype' on importing .ptu file

### ISSUE THREAD

**Issue by nranthony** [dwaithe/FCS_point_correlator#22]
Hi Dominic,
Alas, I still get an error on opening .ptu files.  This time it's:
```
Traceback (most recent call last):
File "C:\cygwin64\home\dominic\build\FCS_point\out00-PYZ.pyz\correlation_gui", line 213, in showDialog
File "C:\cygwin64\home\dominic\build\FCS_point\out00-PYZ.pyz\correlation_objects", line 60, in __init__
File "C:\cygwin64\home\dominic\build\FCS_point\out00-PYZ.pyz\correlation_objects", line 78, in processData
File "C:\cygwin64\home\dominic\build\FCS_point\out00-PYZ.pyz\import_methods", line 137, in ptuimport
AttributeError: 'int' object has no attribute 'astype'
```
Here's a ptu file of noise from some testing a little while back.  It opens with PQ code (in fact using a port of the PQ code to a matlab mex file, see https://github.com/nranthony/TTTR/tree/master/PTU, but same horse, different jockey)
[sFCStest_1_TimeHarp_2021-02-14_12-17-43.zip](https://github.com/dwaithe/FCS_point_correlator/files/6620578/sFCStest_1_TimeHarp_2021-02-14_12-17-43.zip)

Thanks in advance for your time.
Neil

**Comment by dwaithe** [comment]
Hi Neil,
I tested your file this morning and it worked fine on Windows and Mac. See attached screenshot. Can I confirm which version you're using? https://github.com/dwaithe/FCS_point_correlator/releases
The latest version 16.201, is the one I am using. I've pushed a number of updates around this issues and so maybe you have an older release?
Let me know.
Best,
dominic.

<img width="1027" alt="Screenshot 2021-06-09 at 07 57 34" src="https://user-images.githubusercontent.com/4719022/121307929-69f46100-c8f8-11eb-9896-c6824d307068.png">

**Comment by nranthony** [comment]
Hi Dominic, thanks for the speedy reply.

The latest release that you're using above, that I download here https://github.com/dwaithe/FCS_point_correlator/releases/tag/1.16.201 does not have an exe file.  I instead went to http://dwaithe.github.io/FCS_point_correlator/ and I downloaded using the Win zip file here:

![image](https://user-images.githubusercontent.com/16306836/121531902-d80a5800-c9cc-11eb-9cb6-ce9ba480873a.png)

Turns out, looking at folder names, that the download from the .io page is 1.13.

Out of curiosity, what's the best way to run and debug the code using the python files?

Sorry for my confusion on files and version.
Thanks
Neil

**Comment by dwaithe** [comment]
Hi Neil,
When you click on the latest releases, if you read the text, you will find a link to the windows exe. I put it here for your ease:
https://drive.google.com/file/d/1cvlqRe1kdefo1dcgJeTdwUJ6Kk9t-_Fq/view?usp=sharing
When you click here and download the zip file, the .exe will be inside. The 1.13 is the original published version, but I will remove that now, it is really out of date.
Best,
Dominic.

**Comment by nranthony** [comment]
Wonderful, thanks.  I got things open and imported.  I'll take a look at the manual and go from there.
Thanks
