### ISSUE TITLE
Crash on macOS Big Sur Version 11.4

### ISSUE THREAD

**Issue by SiuShingWong** [dwaithe/FCS_point_correlator#23]
Hi Dominic,

I've successfully loaded the FCS data but immediately after I loaded models, the program crashed and shut down. Would you mind to have a look? Many thanks.

Best,
Isaac

**Comment by dwaithe** [comment]
HI Isaac, 
I would definitely try the latest version (1.16.201):
https://github.com/dwaithe/FCS_point_correlator/releases/tag/1.16.201

If that doesn't work, would you be able to share some data with me? You can attach it here, or email it to: dominic.waithe@imm.ox.ac.uk. It is unlikely to be Big Sur, but more likely some aspect of your data.
Thanks,
Best,
Dominic.

**Comment by dwaithe** [comment]
The load profile bug has been fixed in 1.16.202.
Thanks for reporting.
