### ISSUE TITLE
Loading .fcs files from Zeiss780/880/980 to FoCuS or FCSfitJS

### ISSUE THREAD

**Issue by Faldalf** [dwaithe/FCS_point_correlator#24]
Hi Dominic, 

using the most recent version of FoCuS_point (16_202) as well as the FCSfitJS version I run into trouble opening .fcs files from Zeiss machines: Not all measurements are displayed and you cannot dispaly the second channel. 
This worked fine in previous versions (here FoCuS_scan_14_74):
![FCS_issue](https://user-images.githubusercontent.com/66516920/127754562-fc4140b8-a2aa-4c0f-a96a-79e449eafb4e.png)

I attached two example files (dual-colour, no CC and dual-colour with CC
[FCS_files_DualColour.zip](https://github.com/dwaithe/FCS_point_correlator/files/6911940/FCS_files_DualColour.zip)
)

It just seems like there's something funny about assinging and reading the channels. 

Many thanks, 
Falk

**Comment by dwaithe** [comment]
Thanks Falk,
Latest version reverts the reader to the older method.
https://github.com/dwaithe/FCS_point_correlator/releases/tag/1.16.203
Best,
Domnic.
