### ISSUE TITLE
Data series viewer naming convention

### ISSUE THREAD

**Issue by SiuShingWong** [dwaithe/FCS_point_correlator#25]
Hi,

I think the current version cannot reflect the change of file name in the data series viewer. If we have a huge dataset comprising several comparison sets which are not in consecutive order or image on the same day, it is not possible to distinguish them after the fitting. I think it currently reflect the name in the .fcs file but not on the file name. Is it possible to revert this feature to an older version? Many thanks,
Isaac

<img width="1202" alt="Screen Shot 2021-08-24 at 12 42 27 PM" src="https://user-images.githubusercontent.com/25399945/130611033-43f239a2-7f24-4117-9bfb-d085d7bc466c.png">
<img width="1205" alt="Screen Shot 2021-08-24 at 12 42 41 PM" src="https://user-images.githubusercontent.com/25399945/130611040-3636c6d3-592e-4958-842e-30d520ed3f65.png">

**Comment by dwaithe** [comment]
Hi Isaac,
Thanks for this. Another user has had same problem.
I have reverted the .fcs importer. Please see the latest release:
https://github.com/dwaithe/FCS_point_correlator/releases/tag/1.16.203
Best,
Dominic.
