### ISSUE TITLE
a bit more doccumentation

### ISSUE THREAD

**Issue by biswajitSM** [dwaithe/FCS_point_correlator#3]
Is it possible to add a bit more documentation on how the inputs are given? I was trying to run "auto, autotime = tttr2xfcs (y=t*unit,num=10, NcascStart=1e-6,NcascEnd=1, Nsub=5)" where 't' is the arrival time of photons.  However it's not clear what each of these variable means especially 'num'.

Thanks for your time and the code.
Biswajit

**Comment by dwaithe** [comment]
Hi Biswajit,
I have added much more explanation to make it clearer:
https://github.com/dwaithe/FCS_point_correlator/blob/master/focuspoint/correlation_methods.py

I think however you might need a more generic correlation algorithm. The tttr2xfcs algorithm is for time-tag data where every photon arrival time is unique and not at set intervals. Please refer to: https://github.com/dwaithe/FCS_point_correlator/blob/master/focuspoint/test_script.py
The example at the bottom shows how the data would normally be formated. In effect, you correlate the arrival times, not the intensity level at different time bins, which is normally the case. If formatted correctly your data will work, you need to replace your num ('10') with something like np.one(t.shape[0],2), but I would recommend one of the correlation algorithms described here:
https://github.com/dwaithe/generalMacros/blob/master/diffusion%20simulations%20/Correlate%20Comparison.ipynb

I hope that helps.
Best,
Dominic
