### ISSUE TITLE
Separate GUI from algorithms using submodules

### ISSUE THREAD

**Issue by paulmueller** [dwaithe/FCS_point_correlator#4]
I am using some of the functionalities of focuspoint in PyCorrFit. Currently, I believe the version I am using is very outdated. To incorporate focuspoint funcitonalities in PyCorrFit (including new file formats), I usually have to update my wrapper which is time-consuming.

Would it be possible for you to create separate submodules (separate folders with `__init__.py` file) for file reading, data correlation, and fitting algorithms (that do not contain any PyQt dependencies)? 

I know this probably takes some time, but it would help me a lot.

Cheers,
Paul

**Comment by dwaithe** [comment]
Hi Paul,
Yeah thats a good idea. It is time. I will let you know how I get on with it.
Best,
Dominic

**Comment by dwaithe** [comment]
It took a while but it is happening. I have also gone to py3. Hopefully this won't break everything..
