### ISSUE TITLE
Support for PT2 format (picoharp 300)

### ISSUE THREAD

**Issue by MehranUTS** [dwaithe/FCS_point_correlator#5]
Is it possible to include supporting for Pt2 format? ( It is for picoharp 300)

https://github.com/PicoQuant/PicoQuant-Time-Tagged-File-Format-Demos/tree/master/legacy/PicoHarp%20filedemos/pt2/matlab

**Comment by dwaithe** [comment]
Hi, yes that would be no problem. Do you have any files however? This would make it but easier for me to debug the reader.

**Comment by MehranUTS** [comment]
Many thanks. This is great. The Pt2 file are usually big files. I have one file which is about 15MB. Here is the link to is:

https://drive.google.com/open?id=0B6d4FQspSzCaMDRRNG5CbnU0VFk

**Comment by dwaithe** [comment]
Hi MehranUTS,
I have managed to implement the code for opening the PT2 files. I have compared the correlations with those produced by SymPhoTime software and they are the same. Do you use FoCuS-point as a downloaded file or do you use it by running the python files from the repository? I can quickly push the edits to the github, but it will take me a bit longer to recompile the code to make the software, that is all. Also your curves did look a bit funny, which is an acquisition issue given that they were the same as when using SymPhoTime. Just so you know.
Best,
Dominic.
![screen shot 2017-10-11 at 16 59 20](https://user-images.githubusercontent.com/4719022/31451995-90a129b2-aea5-11e7-9850-7c68d69bc63d.png)

**Comment by MehranUTS** [comment]
Hi Dominic

This is fantastic. Thank you very much. I download the compiled version. However I can try using the python version. I am a beginner in python though. Hopefully there is some "Starting" documentations for this software.

The file that I sent you was recorded from a single photon emitter however the acquisition was not  enough as you noticed (sorry about this). I am particularly interested in looking to short correlation (ps-ns range) as well as long correlation (ms to seconds). I have a complete dataset that will try with your software later. 

Regards
Mehran

**Comment by dwaithe** [comment]
Hi Mehran,
I have updated the Windows and Linux versions of the software and I have also added manuals for the correlation and fitting part of the software to help you get going. I will likely add the latest version of the software for mac next week. 
Best,
Dominic

**Comment by MehranUTS** [comment]
Hi Dominic
I have downloaded the updated version of FoCus. I wasn't able to load the pt2 file though (the same file I sent you). When I open the file with the software, it shows " processing file1 of 1" in green color at the bottom and nothing else happen after (or should I wait longer?)
![capture](https://user-images.githubusercontent.com/32559970/31651647-3b15ed30-b368-11e7-8fa2-44f7be369a30.PNG)
. On the back window, there is an error: "AttributeError: picoObject instance has no attribute  'timeseriesScale1' . I am not sure what is the problem.

Also where can I find the manuals?  maybe through manuals I can get rid of this issue. 

Many thanks
Mehran

**Comment by dwaithe** [comment]
Hi Mehran,
The issuse is that you have not downloaded the latest release. I can tell from the top of your image which says 1_13_130. The latest release is at the top of the release page, here is a quick link: https://github.com/dwaithe/FCS_point_correlator/releases/tag/1.13.152
Please download it and replace your existing verison. It should then work fine with the pt2 files.
Best wishes,
Dominic
p.s. sorry for my slow reply I was away on a workshop with intermittent email.

**Comment by MehranUTS** [comment]
Hi Dominic,

Thanks for your reply. I replaced the new version and it works very nice with pt2 files as you said. However the saved output file doesn't seems right! Am I  doing something wrong again? Here is the saved file:
[g2-long-02_correlation.zip](https://github.com/dwaithe/FCS_point_correlator/files/1409004/g2-long-02_correlation.zip)

Also,  in the current version correlation is plotted from 1ns delay time to seconds, is this software able to get the correlation from zero delay time  to see the anti-bunching as well?

Regards
Mehran

**Comment by dwaithe** [comment]
Hi,
Regarding saving, you are right there is a bug there. Thanks for bringing it to my attention. As a work-around you can goto the 'Fit Function' tab and use the Save:  'plot data' function. Though you have to fit the data before it will be included in the exported data.
![screen shot 2017-10-24 at 15 29 59](https://user-images.githubusercontent.com/4719022/31949520-7397f05e-b8d1-11e7-9c70-ca20f3e60d9a.png)
I have fixed the software for this bug and will update the release as soon as I get the chance, but hopefully you can extract your data with the above method in the meantime.

Regarding zero delay time, this at the moment is not possible with this method without some significant re-engineering. 1 ns is the minimum resolution. I could maybe introduce it if it is something you really wanted?

Best,
Dominic

**Comment by MehranUTS** [comment]
Hi,

Ultimately, I want to have full correlation (from 0 to seconds) as I am working with single photon emitters. However this might be too much to ask. I should  learn some python! 

Many thanks for your help
Best
Mehran
