### ISSUE TITLE
Filtering intensy 

### ISSUE THREAD

**Issue by RuddiRodriguez** [dwaithe/FCS_point_correlator#7]
is there a way to filter the intensity traces before correlation ? 
Thank you

**Comment by dwaithe** [comment]
How Ruddi, The Intensity traces are just for visualisation in the FoCuS-point software. The raw data is individual photons with TCSPC detectors. Using the interface you can filter TCSPC photons based on arrival time, if that is what you mean? This will affect the correlation. The intensity trace in the software is created as a visualisation and is independent of the correlation process which focuses on the individual photons.
