### ISSUE TITLE
.spc import only handles channel 0

### ISSUE THREAD

**Issue by AndreasSchoenle** [dwaithe/FCS_point_correlator#9]
See e.g. this file:
[bhspcm_2019-04-03_12-07-51.zip](https://github.com/dwaithe/FCS_point_correlator/files/3044602/bhspcm_2019-04-03_12-07-51.zip)
See also my pull request.

There is one more issue - for some reason there is a single count in channel 3 (may be an issue with the router, I did not collect the data myself) which leads to the x-correlation and correlation for channel 3 also being displayed. The normalization methods throw some Exceptions and the display stays empty, I did not debug through why.

**Comment by dwaithe** [comment]
Hi,
Thanks for this. I will look into it and get back to you. I need to work on some other files and so this is good timing.
Best,
Dominic

**Comment by AndreasSchoenle** [comment]
Thanks for the quick answer. In case you are currently going though your code, you could have a look at 
[the python3-pyqt5 branch](https://github.com/AbberiorInstruments/FCS_point_correlator/tree/python3-pyqt5), too. Foolishly, before actually looking to find the reader bug I had thought that porting to PyQt5 and Python3 would be less work than installing Anaconda2 and meeting dependencies. 

Besides the change to print() and the naming in PyQt4 vs PyQt5 it seems like the file dialog now returns a tuple with the file list being the first element, the filter in use the second. Also cPickle is now just pickle and `threads` is deprecated but still available as `threads_`. 

After fixing these, I got to where it loads .spc files but it seems I broke the fitting GUI somehow.
Maybe it is related to QStandardItem not being hashable any more, so I replaced `[item]` with `[id(item)]` in one instance. I then ran out of time and did the smart thing, debugging under Python 2.7.

Anyhow, if you were ever thinking about going python3 and pyqt5, maybe the WIP is useful as a starting point. The remaining issues might be a quick fix with intimate knowledge of your program structure. Let me know in case you want me to create a merge request - I hesitated as the head of the branch is not in a working state.

Also, **I believe that fitting_methods and import_methods sub modules are missing from the setup.py** also in your master. So maybe you can cherry-pick 64ade5bbd0909c2f7741befb8b3c53d973fb596e and 0ef23994311a4cab174e37feacb0118ab1ded55a directly.

Best and thanks again!
Andreas

**Comment by dwaithe** [comment]
HI Andreas,
The latest commit should be fully python3. I've been looking at your .SPC file. Do you know what version of SPC it is? Did it come with other files when you saved it (e.g. .sdt .set?)

**Comment by dwaithe** [comment]
I can see that in your .spc file the main channel is 2, not zero which is normal. I have just added in support for channels 1, and 2. Let me know how you get on. I have just pushed up the commit with this new feature.

**Comment by AndreasSchoenle** [comment]
Wow, this is great! Thanks for porting to py3 so quickly.

About the .spc file: It is the raw data as received from and SPC-150 B&H card. Our software uses the spcm32.dll API. All measurements are done in FIFO Image mode and the SW reads the stream directly from the card, interprets it in order to create images, split photons into channels, and build up histograms if requested. For more advanced users, there is an option to also write the data directly to disk as .spc file with the appropriate 32bit binary header DWORD as specified in the B&H header file for this card.

This is mainly for customers that already have their own MATLAB or Python based toolchain that is capable of doing advanced analysis on this data.
I have therefore no accompanying .sdt and .set files - metadata beyond what can be inferred from the photon stream is usually retrieved from the .msr files that our software writes which contains much more information specific to our instrument - like laser switching patterns, ROI, dwell times, laser powers etc. 

As explained in my comment to the commit, our hardware configuration often has 4 or - in the presence of e.g. an alternative non-descanned lightpath - even more detectors attached to the router which are then used in various combinations.
